### ISSUE TITLE
Load Audio from storage

### ISSUE THREAD

**Issue by praharshbhatt** [fireslime/flutter_gapless_audio_loop#2]
Playing audio from assets folder works flawlessly, but loading an audio file saved onto the device gives an error:

Code
```
final player = GaplessAudioLoop();
await player.load(srtPath);

await player.play();
```
where the path of the file is: "/data/user/0/com.dhrupadacademy.dhrupad_gurukul/files/Dhaamr 3 C sharp.m4a"

Error:
```
11:38:52.449 1 info flutter.tools E/flutter (30621): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets//data/user/0/com.dhrupadacademy.dhrupad_gurukul/files/Dhaamr 3 C sharp.m4a
11:38:52.449 2 info flutter.tools E/flutter (30621): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
11:38:52.449 3 info flutter.tools E/flutter (30621): <asynchronous suspension>
11:38:52.449 4 info flutter.tools E/flutter (30621): #1      GaplessAudioLoop._fetchAsset (package:gapless_audio_loop/gapless_audio_loop.dart:29:29)
11:38:52.449 5 info flutter.tools E/flutter (30621): <asynchronous suspension>
11:38:52.449 6 info flutter.tools E/flutter (30621): #2      GaplessAudioLoop._fetchToMemory (package:gapless_audio_loop/gapless_audio_loop.dart:36:30)
11:38:52.449 7 info flutter.tools E/flutter (30621): <asynchronous suspension>
11:38:52.449 8 info flutter.tools E/flutter (30621): #3      GaplessAudioLoop.load (package:gapless_audio_loop/gapless_audio_loop.dart:46:25)
11:38:52.449 9 info flutter.tools E/flutter (30621): <asynchronous suspension>
11:38:52.449 10 info flutter.tools E/flutter (30621): #4      _MyHomePageState.build.<anonymous closure> (package:gapless_audio_loop_example/main.dart:46:32)
11:38:52.449 11 info flutter.tools E/flutter (30621): <asynchronous suspension>
11:38:52.449 12 info flutter.tools E/flutter (30621): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:659:14)
11:38:52.449 13 info flutter.tools E/flutter (30621): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:734:32)
11:38:52.450 14 info flutter.tools E/flutter (30621): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
11:38:52.450 15 info flutter.tools E/flutter (30621): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
11:38:52.450 16 info flutter.tools E/flutter (30621): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
11:38:52.450 17 info flutter.tools E/flutter (30621): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
11:38:52.450 18 info flutter.tools E/flutter (30621): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
11:38:52.450 19 info flutter.tools E/flutter (30621): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
11:38:52.450 20 info flutter.tools E/flutter (30621): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
11:38:52.450 21 info flutter.tools E/flutter (30621): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
11:38:52.450 22 info flutter.tools E/flutter (30621): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
11:38:52.450 23 info flutter.tools E/flutter (30621): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
11:38:52.450 24 info flutter.tools E/flutter (30621): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
11:38:52.450 25 info flutter.tools E/flutter (30621): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
11:38:52.450 26 info flutter.tools E/flutter (30621): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
11:38:52.450 27 info flutter.tools E/flutter (30621): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
11:38:52.451 28 info flutter.tools E/flutter (30621): #21     _invoke1 (dart:ui/hooks.dart:263:10)
11:38:52.451 29 info flutter.tools E/flutter (30621): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
11:38:52.451 30 info flutter.tools E/flutter (30621): 
11:38:53.240 31 info runtime.gc collection time 98ms • 50.3MB used of 66.4MB • isolates/2968880481902839
11:38:53.240 32 info runtime.gc collection time 165ms • 46.5MB used of 62.9MB • isolates/2968880481902839

```

Any solution?
Thanks

**Comment by praharshbhatt** [comment]
I see the issue now
it already has the prefix "assets/" so it always takes asset files.

Is it possible for us to give an absolute path?

**Comment by erickzanardo** [comment]
Yeah, should be an easy change, going to change that when I get the chance

**Comment by erickzanardo** [comment]
Done on `1.1.0` (https://pub.dev/packages/gapless_audio_loop/versions/1.1.0)

Note that the are breaking changes `load` method now is `loadAsset` and the method to load the file on the device storage is `loadFile`.

Let me know if there is any problem.
