### ISSUE TITLE
Problem: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by nohli** [fireslime/flutter_gapless_audio_loop#9]
Every once in a while the Pre-Launch-Report (Goole Play) gives me this warning.

In the simulator videos there is no visible crash (also no recorded audio, so if the audio stopped, I couldn't hear it). But maybe this is an issue? Maybe I did something wrong? Just wanted to let you know.

<details>
  <summary>Logs</summary>

```
FATAL EXCEPTION: main
Process: com.achimsapps.breathe, PID: 14428
java.lang.IllegalStateException
	at android.media.MediaPlayer.setNextMediaPlayer(Native Method)
	at i.a.a.b$b.onPrepared()
	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2815)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

```
FATAL EXCEPTION: main
Process: com.achimsapps.breathe, PID: 25593
java.lang.IllegalStateException
	at android.media.MediaPlayer.setNextMediaPlayer(Native Method)
	at i.a.a.b$b.onPrepared()
	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2821)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

</details>

**Comment by erickzanardo** [comment]
This package is no longer maintained, I have create a [new package](https://github.com/erickzanardo/ocarina) to support gapless loop

**Comment by nohli** [comment]
Hi @erickzanardo
Thanks for the information!
Is is safe(r) to switch to your new plugin (although it‘s 0.0.1) right now?

**Comment by erickzanardo** [comment]
Should be, I did a bunch of tests and it worked great. Feel free to open issues there if you encounter any problem.

**Comment by nohli** [comment]
Also for normal audio without loop (like/ replacing audioplayers)?

Thanks for your work and help!! :)

Edit:
Today I‘ve replaced both audioplayers and gapless_audio_loop with ocarina and have no build warnings for the first time. It works great. 👍🏼

The only 'drawback', but that has just been a lucky workaround on my side: Somehow gapless_audio_loop kept the app/ ui 'awake' when going to background and both audio plugins would keep playing (even new sounds). Now on iOS it stops when going to background, and resumes when the app is reopened.
